import { test, expect } from "@playwright/test";
import * as XLSX from "xlsx";
import { createWorkbook } from "../../src/lib/excel.js";
import { seedRecords } from "../../src/lib/seed.js";
import { mkdir, readFile } from "node:fs/promises";
async function login(page) {
  await page.goto("/login");
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await expect(page.getByRole("table")).toBeVisible();
}
test("authentication protects records and the reference screens render cleanly", async ({page,request}) => {
  const errors=[]; page.on("pageerror",e=>errors.push(e.message));
  expect((await request.get("/api/ib-records")).status()).toBe(401);
  await page.goto("/ib-records");
  await expect(page).toHaveURL(/\/login$/);
  await mkdir("artifacts",{recursive:true});
  await page.screenshot({path:"artifacts/login-desktop.png",fullPage:true});
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("table")).toBeVisible();
  await expect(page.locator(".record-count")).toHaveText("324 records");
  await expect(page.locator("tbody tr")).toHaveCount(25);
  await page.screenshot({path:"artifacts/records-desktop.png",fullPage:true});
  await page.getByRole("button",{name:"View 5 social links for FX Academy"}).first().click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("dialog").getByRole("link")).toHaveCount(5);
  await page.screenshot({path:"artifacts/social-dialog-desktop.png",fullPage:true});
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("link",{name:"Add IB Data",exact:true}).click();
  await expect(page.getByRole("button",{name:"Save IB Record"})).toBeVisible();
  await page.screenshot({path:"artifacts/add-manual-desktop.png",fullPage:true});
  await page.getByRole("tab",{name:"Import Excel"}).click();
  await page.screenshot({path:"artifacts/import-desktop.png",fullPage:true});
  expect(errors).toEqual([]);
});
test("search, filter chips, sorting, pagination and full-result export work together", async ({page}) => {
  await login(page);
  await page.getByRole("button",{name:"Next page",exact:true}).click();
  await expect(page.locator(".pagination > span")).toHaveText("26–50 of 324 records");
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("FX Academy");
  await expect(page.locator(".record-count")).toHaveText("24 records");
  await page.getByRole("button",{name:"Clear search",exact:true}).click();
  await page.getByRole("complementary",{name:"Record filters"}).getByRole("button",{name:"Country",exact:true}).click();
  await page.getByRole("textbox",{name:"Search country options"}).fill("United Arab");
  await page.locator(".select-options").getByRole("checkbox").check();
  await page.getByRole("complementary",{name:"Record filters"}).getByRole("button",{name:"Country",exact:true}).click();
  await page.getByRole("button",{name:"Apply Filters"}).click();
  await expect(page.locator(".record-count")).toHaveText("24 records");
  await expect(page.getByRole("button",{name:"Remove UAE filter"})).toBeVisible();
  await page.getByRole("button",{name:"Remove UAE filter"}).click();
  await page.getByRole("columnheader",{name:"Total Salary"}).getByRole("button").click();
  await page.getByRole("columnheader",{name:"Total Salary"}).getByRole("button").click();
  await expect(page.getByRole("columnheader",{name:"Total Salary"})).toHaveAttribute("aria-sort","descending");
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("Sneha");
  await expect(page.locator(".record-count")).toHaveText("70 records");
  await page.getByRole("button",{name:"Export",exact:true}).click();
  const downloadEvent=page.waitForEvent("download");
  await page.getByRole("button",{name:"Export current results"}).click();
  const download=await downloadEvent;
  const book=XLSX.read(await readFile(await download.path()),{type:"buffer"});
  const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]);
  expect(rows).toHaveLength(70);
  expect(rows.every(r=>r["PSM Name"]==="Sneha Patel")).toBe(true);
  expect(rows[0]["Total Salary"]).toBe(6800);
  await page.getByRole("button",{name:"Export",exact:true}).click();
  const allDownloadEvent=page.waitForEvent("download");
  await page.getByRole("button",{name:"Export all records"}).click();
  const allDownload=await allDownloadEvent;
  const allBook=XLSX.read(await readFile(await allDownload.path()),{type:"buffer"});
  expect(XLSX.utils.sheet_to_json(allBook.Sheets[allBook.SheetNames[0]])).toHaveLength(324);
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("no-matching-client");
  await expect(page.getByText("No records found", {exact:true})).toBeVisible();
  await expect(page.locator(".pagination > span")).toHaveText("0–0 of 0 records");
});
test("manual add, platform validation, persistence and record editing work", async ({page}) => {
  await login(page);
  await page.goto("/ib-records/add");
  await page.getByRole("button",{name:"Save IB Record"}).click();
  await expect(page.getByText("Select a valid country.",{exact:true})).toBeVisible();
  await page.getByLabel("Country",{exact:true}).click();
  await page.getByRole("combobox",{name:"Search countries"}).fill("India");
  await page.getByRole("option",{name:"India",exact:true}).click();
  await page.getByLabel("Client Name",{exact:true}).fill("QA Persistence Client");
  await page.getByLabel("Channel Name",{exact:true}).fill("QA Demo Channel");
  await page.getByLabel("PSM Name",{exact:true}).fill("QA Accountant");
  await page.getByLabel("IB Commission / Lot",{exact:true}).fill("12.5");
  await page.getByLabel("Spreads",{exact:true}).fill("1.2");
  await page.getByLabel("Upfront Paid",{exact:true}).fill("2500");
  await page.getByLabel("Total Salary",{exact:true}).fill("6000");
  await page.getByLabel("Payout Date",{exact:true}).fill("2026-10-01");
  await page.getByLabel("YouTube URL",{exact:true}).fill("https://google.com");
  await page.getByRole("button",{name:"Save IB Record"}).click();
  await expect(page.getByText("Enter a valid HTTPS YouTube URL.",{exact:true})).toBeVisible();
  await page.getByLabel("YouTube URL",{exact:true}).fill("https://youtube.com/@qademo");
  await page.getByRole("button",{name:"Save IB Record"}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await page.reload();
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("QA Persistence Client");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await page.getByRole("button",{name:"Actions for QA Persistence Client"}).click();
  await page.getByRole("button",{name:"Edit record",exact:true}).click();
  await page.getByLabel("Total Salary",{exact:true}).fill("6500");
  await page.getByRole("button",{name:"Save Changes"}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("QA Persistence Client");
  await expect(page.locator("tbody")).toContainText("$6,500.00");
});
test("Excel preview prevents invalid and duplicate rows from being silently committed", async ({page}) => {
  await login(page);
  const existing=seedRecords()[0];
  const newRecord={...existing,clientName:"QA Excel Client",channelName:"QA Excel Channel"};
  const badRecord={...existing,clientName:"QA Invalid Client",payoutDate:"not-a-date"};
  const payload=createWorkbook([newRecord,existing,badRecord]);
  await page.goto("/ib-records/add");
  await page.getByRole("tab",{name:"Import Excel"}).click();
  await page.getByLabel("Upload Excel file",{exact:true}).setInputFiles({name:"qa-records.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:payload});
  await expect(page.getByText("3 rows detected",{exact:true})).toBeVisible();
  await expect(page.getByText("1 Possible duplicates",{exact:true})).toBeVisible();
  await expect(page.getByText("1 Invalid",{exact:true})).toBeVisible();
  const before=await (await page.request.get("/api/ib-records")).json();
  expect(before.records.some(r=>r.clientName==="QA Excel Client")).toBe(false);
  await page.getByRole("button",{name:"Import 1 valid records",exact:true}).click();
  await expect(page.getByText("Import complete",{exact:true})).toBeVisible();
  await expect(page.getByText("1 added · 0 updated · 2 skipped",{exact:true})).toBeVisible();
  const after=await (await page.request.get("/api/ib-records")).json();
  expect(after.records.some(r=>r.clientName==="QA Excel Client")).toBe(true);
  expect(after.records.some(r=>r.clientName==="QA Invalid Client")).toBe(false);
  // The server repeats validation even if a client tries to bypass the preview.
  const response=await page.request.post("/api/import",{data:{inputs:[{...newRecord,totalSalary:7000},badRecord],duplicateMode:"update"}});
  expect(await response.json()).toEqual({added:0,updated:1,skipped:1});
  const updated=await (await page.request.get("/api/ib-records")).json();
  expect(updated.records.find(r=>r.clientName==="QA Excel Client").totalSalary).toBe(7000);
});
test("mobile keeps a scrollable table and filters open in a drawer", async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await login(page);
  await page.screenshot({path:"artifacts/records-mobile.png",fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(await page.locator(".table-scroll").evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);
  await page.getByRole("button",{name:"Filters",exact:true}).click();
  await expect(page.getByRole("complementary",{name:"Record filters"})).toBeVisible();
  await page.screenshot({path:"artifacts/filters-mobile.png",fullPage:true});
  await page.getByRole("button",{name:"Close filters",exact:true}).last().click();
  await page.goto("/ib-records/add");
  await page.screenshot({path:"artifacts/add-mobile.png",fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test("logout revokes browser access and forged sessions are rejected", async ({page,context}) => {
  await login(page);
  await page.getByRole("button",{name:/Accountant/}).click();
  await page.getByRole("button",{name:"Sign out",exact:true}).click();
  await expect(page).toHaveURL(/\/login$/);
  expect((await page.request.get("/api/ib-records")).status()).toBe(401);
  await context.addCookies([{name:"bytefx_session",value:"forged.signature",url:"http://127.0.0.1:3100"}]);
  expect((await page.request.get("/api/ib-records")).status()).toBe(401);
});

test("custom calendar supports month selection, keyboard navigation, clearing and mobile filters", async ({page}) => {
  await login(page);
  await expect(page.locator('.header-product-name')).toContainText('Management System');
  await page.goto('/ib-records/add');
  await expect(page.locator('.header-product-name')).toHaveCount(0);
  await page.getByRole('button',{name:'Choose payout date',exact:true}).click();
  const calendar=page.getByRole('dialog',{name:'Payout date calendar'});
  await expect(calendar).toBeVisible();
  await calendar.getByLabel('Calendar year').selectOption('2028');
  await calendar.getByLabel('Calendar month').selectOption('1');
  await page.screenshot({path:'artifacts/calendar-desktop.png',fullPage:true});
  await calendar.getByRole('button',{name:'Tuesday, February 29, 2028'}).click();
  await expect(page.getByLabel('Payout Date',{exact:true})).toHaveValue('2028-02-29');
  await page.getByRole('button',{name:'Choose payout date',exact:true}).click();
  await page.keyboard.press('ArrowRight');
  await page.keyboard.press('Enter');
  await expect(page.getByLabel('Payout Date',{exact:true})).toHaveValue('2028-03-01');
  await page.getByRole('button',{name:'Choose payout date',exact:true}).click();
  await calendar.getByRole('button',{name:'Clear',exact:true}).click();
  await expect(page.getByLabel('Payout Date',{exact:true})).toHaveValue('');
  await page.setViewportSize({width:390,height:844});
  await page.goto('/ib-records');
  await page.getByRole('button',{name:'Filters',exact:true}).click();
  await page.getByRole('button',{name:'Choose payout from date',exact:true}).click();
  const mobileCalendar=page.getByRole('dialog',{name:'Payout from date calendar'});
  await expect(mobileCalendar).toBeVisible();
  await page.screenshot({path:'artifacts/calendar-mobile.png',fullPage:true});
  const box=await mobileCalendar.boundingBox();
  expect(box.x).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(390);
  await mobileCalendar.getByRole('button',{name:'Today',exact:true}).click();
  await expect(page.getByLabel('Payout from date',{exact:true})).not.toHaveValue('');
});

test("deletion requires authentication and exact saved client name and persists after reload", async ({page,request}) => {
  expect((await request.delete('/api/ib-records/anything',{data:{clientName:'Test'}})).status()).toBe(401);
  await login(page);
  const response=await page.request.post('/api/ib-records',{data:{...seedRecords()[0],clientName:'QA Delete Client',channelName:'QA Delete Channel'}});
  expect(response.ok()).toBe(true);
  const {record}=await response.json();
  expect((await page.request.delete(`/api/ib-records/${record.id}`,{data:{clientName:'qa delete client'}})).status()).toBe(400);
  expect((await page.request.delete(`/api/ib-records/${record.id}`,{headers:{Origin:'https://example.com'},data:{clientName:record.clientName}})).status()).toBe(403);
  await page.goto(`/ib-records/add?edit=${record.id}`);
  await page.getByLabel('Client Name',{exact:true}).fill('Unsaved name');
  await page.getByRole('button',{name:'Delete record',exact:true}).click();
  const dialog=page.getByRole('dialog',{name:'Delete IB record?'});
  await expect(dialog).toContainText('QA Delete Client');
  await expect(dialog.getByRole('button',{name:'Permanently delete record'})).toBeDisabled();
  await dialog.getByRole('textbox').fill('qa delete client');
  await expect(dialog.getByRole('button',{name:'Permanently delete record'})).toBeDisabled();
  await dialog.getByRole('button',{name:'Cancel',exact:true}).click();
  await expect(dialog).toHaveCount(0);
  await page.getByRole('button',{name:'Delete record',exact:true}).click();
  await dialog.getByRole('textbox').fill('QA Delete Client');
  await dialog.getByRole('button',{name:'Permanently delete record'}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await page.reload();
  await page.getByRole('textbox',{name:'Search records',exact:true}).fill('QA Delete Client');
  await expect(page.locator('tbody tr')).toHaveCount(0);
  expect((await page.request.delete(`/api/ib-records/${record.id}`,{data:{clientName:record.clientName}})).status()).toBe(404);
});

test("sample download imports and repeats safely; malformed files and formulas show actionable errors", async ({page}) => {
  await login(page);
  await page.goto('/ib-records/add');
  await page.getByRole('tab',{name:'Import Excel'}).click();
  const downloadEvent=page.waitForEvent('download');
  await page.getByRole('link',{name:'Download sample with 5,000 test records'}).click();
  const sample=await downloadEvent;
  let release;
  let gate=new Promise(resolve=>{release=resolve;});
  await page.route('**/api/import',async route=>{await gate;await route.continue();});
  await page.getByLabel('Upload Excel file').setInputFiles({name:sample.suggestedFilename(),mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await readFile(await sample.path())});
  await expect(page.getByRole('dialog',{name:'Preparing your workbook'})).toBeVisible();
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog',{name:'Preparing your workbook'})).toBeVisible();
  release();
  await expect(page.getByText('5000 rows detected',{exact:true})).toBeVisible();
  await expect(page.locator('.preview-table tbody tr')).toHaveCount(100);
  await page.getByRole('button',{name:'Next rows',exact:true}).click();
  await expect(page.locator('.preview-table tbody tr').first()).toContainText('Test IB Client 00101');
  gate=new Promise(resolve=>{release=resolve;});
  await page.getByRole('button',{name:'Import 5000 valid records',exact:true}).click();
  const progress=page.getByRole('dialog',{name:'Importing IB records'});
  await expect(progress).toBeVisible();
  await expect(progress).toContainText('Saving 5,000 records');
  await expect(progress.getByRole('progressbar')).toHaveAttribute('aria-valuetext','In progress');
  await page.screenshot({path:'artifacts/import-progress-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'artifacts/import-progress-mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.setViewportSize({width:1536,height:960});
  release();
  await expect(page.getByText('Import complete',{exact:true})).toBeVisible();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const saved=await (await page.request.get('/api/ib-records')).json();
  expect(saved.records.filter(record=>record.clientName.startsWith('Test IB Client '))).toHaveLength(5000);
  await page.unroute('**/api/import');
  await page.getByLabel('Upload Excel file').setInputFiles({name:sample.suggestedFilename(),mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:await readFile(await sample.path())});
  await expect(page.getByText('5000 Possible duplicates',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Import 0 valid records'})).toBeDisabled();
  await page.getByLabel('Possible duplicates',{exact:true}).selectOption('update');
  await page.getByRole('button',{name:'Import 5000 valid records',exact:true}).click();
  await expect(page.getByText(/0 added.*5000 updated.*0 skipped/)).toBeVisible();
  await page.getByLabel('Upload Excel file').setInputFiles({name:'broken.xlsx',mimeType:'application/octet-stream',buffer:Buffer.from('not excel')});
  await expect(page.locator('.form-error')).toContainText('not a valid Excel workbook');
  const book=XLSX.read(createWorkbook([{...seedRecords()[0],clientName:'Formula Test'}]),{type:'buffer'});
  book.Sheets['IB Records'].E2={t:'n',v:20,f:'10+10'};
  XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet([['Notes']]),'Notes');
  await page.getByLabel('Upload Excel file').setInputFiles({name:'formula.xlsx',mimeType:'application/octet-stream',buffer:XLSX.write(book,{type:'buffer',bookType:'xlsx'})});
  await expect(page.getByText('1 Invalid',{exact:true})).toBeVisible();
  await expect(page.locator('.preview-table')).toContainText('Formulas are not supported');
  await expect(page.locator('.import-warnings')).toContainText('Only the first worksheet');
  await expect(page.getByRole('button',{name:'Import 0 valid records'})).toBeDisabled();
});


test("import loading dialog closes on server failure and allows retry", async ({page}) => {
  await login(page);
  await page.goto('/ib-records/add');
  await page.getByRole('tab',{name:'Import Excel'}).click();
  await page.getByLabel('Upload Excel file').setInputFiles({name:'retry.xlsx',mimeType:'application/octet-stream',buffer:createWorkbook([{...seedRecords()[0],clientName:'Import retry client'}])});
  await expect(page.getByText('1 rows detected',{exact:true})).toBeVisible();
  let release;
  const gate=new Promise(resolve=>{release=resolve;});
  await page.route('**/api/import',async route=>{await gate;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'Temporarily unavailable. Please retry.'})});});
  await page.getByRole('button',{name:'Import 1 valid records',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Importing IB records'})).toBeVisible();
  release();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.locator('.form-error')).toContainText('Temporarily unavailable');
  await expect(page.getByRole('button',{name:'Import 1 valid records',exact:true})).toBeEnabled();
  await page.unroute('**/api/import');
  await page.getByRole('button',{name:'Import 1 valid records',exact:true}).click();
  await expect(page.getByText('Import complete',{exact:true})).toBeVisible();
});
