import { test, expect } from "@playwright/test";
import * as XLSX from "xlsx";
import { createWorkbook } from "../../src/lib/excel.js";
import { seedRecords } from "../../src/lib/seed.js";
import { mkdir, readFile } from "node:fs/promises";
async function login(page) {
  await page.goto("/login");
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await expect(page.getByRole("table")).toBeVisible();
}
test("authentication protects records and the reference screens render cleanly", async ({page,request}) => {
  const errors=[]; page.on("pageerror",e=>errors.push(e.message));
  expect((await request.get("/api/ib-records")).status()).toBe(401);
  await page.goto("/ib-records");
  await expect(page).toHaveURL(/\/login$/);
  await mkdir("artifacts",{recursive:true});
  await page.screenshot({path:"artifacts/login-desktop.png",fullPage:true});
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page.getByRole("table")).toBeVisible();
  await expect(page.locator(".record-count")).toHaveText("324 records");
  await expect(page.locator("tbody tr")).toHaveCount(25);
  await page.screenshot({path:"artifacts/records-desktop.png",fullPage:true});
  await page.getByRole("button",{name:"View 5 social links for FX Academy"}).first().click();
  await expect(page.getByRole("dialog")).toBeVisible();
  await expect(page.getByRole("dialog").getByRole("link")).toHaveCount(5);
  await page.screenshot({path:"artifacts/social-dialog-desktop.png",fullPage:true});
  await page.keyboard.press("Escape");
  await expect(page.getByRole("dialog")).toHaveCount(0);
  await page.getByRole("link",{name:"Add IB Data",exact:true}).click();
  await expect(page.getByRole("button",{name:"Save IB Record"})).toBeVisible();
  await page.screenshot({path:"artifacts/add-manual-desktop.png",fullPage:true});
  await page.getByRole("tab",{name:"Import Excel"}).click();
  await page.screenshot({path:"artifacts/import-desktop.png",fullPage:true});
  expect(errors).toEqual([]);
});
test("search, filter chips, sorting, pagination and full-result export work together", async ({page}) => {
  await login(page);
  await page.getByRole("button",{name:"Next page",exact:true}).click();
  await expect(page.locator(".pagination > span")).toHaveText("26–50 of 324 records");
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("FX Academy");
  await expect(page.locator(".record-count")).toHaveText("24 records");
  await page.getByRole("button",{name:"Clear search",exact:true}).click();
  await page.getByRole("complementary",{name:"Record filters"}).getByRole("button",{name:"Country",exact:true}).click();
  await page.getByRole("textbox",{name:"Search country options"}).fill("United Arab");
  await page.locator(".select-options").getByRole("checkbox").check();
  await page.getByRole("complementary",{name:"Record filters"}).getByRole("button",{name:"Country",exact:true}).click();
  await page.getByRole("button",{name:"Apply Filters"}).click();
  await expect(page.locator(".record-count")).toHaveText("24 records");
  await expect(page.getByRole("button",{name:"Remove UAE filter"})).toBeVisible();
  await page.getByRole("button",{name:"Remove UAE filter"}).click();
  await page.getByRole("columnheader",{name:"Total Salary"}).getByRole("button").click();
  await page.getByRole("columnheader",{name:"Total Salary"}).getByRole("button").click();
  await expect(page.getByRole("columnheader",{name:"Total Salary"})).toHaveAttribute("aria-sort","descending");
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("Sneha");
  await expect(page.locator(".record-count")).toHaveText("70 records");
  await page.getByRole("button",{name:"Export",exact:true}).click();
  const downloadEvent=page.waitForEvent("download");
  await page.getByRole("button",{name:"Export current results"}).click();
  const download=await downloadEvent;
  const book=XLSX.read(await readFile(await download.path()),{type:"buffer"});
  const rows=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]]);
  expect(rows).toHaveLength(70);
  expect(rows.every(r=>r["PSM Name"]==="Sneha Patel")).toBe(true);
  expect(rows[0]["Total Salary"]).toBe(6800);
  await page.getByRole("button",{name:"Export",exact:true}).click();
  const allDownloadEvent=page.waitForEvent("download");
  await page.getByRole("button",{name:"Export all records"}).click();
  const allDownload=await allDownloadEvent;
  const allBook=XLSX.read(await readFile(await allDownload.path()),{type:"buffer"});
  expect(XLSX.utils.sheet_to_json(allBook.Sheets[allBook.SheetNames[0]])).toHaveLength(324);
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("no-matching-client");
  await expect(page.getByText("No records found", {exact:true})).toBeVisible();
  await expect(page.locator(".pagination > span")).toHaveText("0–0 of 0 records");
});
test("manual add, platform validation, persistence and record editing work", async ({page}) => {
  await login(page);
  await page.goto("/ib-records/add");
  await page.getByRole("button",{name:"Save IB Record"}).click();
  await expect(page.getByText("Select a valid country.",{exact:true})).toBeVisible();
  await page.getByLabel("Country",{exact:true}).selectOption("IN");
  await page.getByLabel("Client Name",{exact:true}).fill("QA Persistence Client");
  await page.getByLabel("Channel Name",{exact:true}).fill("QA Demo Channel");
  await page.getByLabel("PSM Name",{exact:true}).fill("QA Accountant");
  await page.getByLabel("IB Commission / Lot",{exact:true}).fill("12.5");
  await page.getByLabel("Spreads",{exact:true}).fill("1.2");
  await page.getByLabel("Upfront Paid",{exact:true}).fill("2500");
  await page.getByLabel("Total Salary",{exact:true}).fill("6000");
  await page.getByLabel("Payout Date",{exact:true}).fill("2026-10-01");
  await page.getByLabel("YouTube URL",{exact:true}).fill("https://google.com");
  await page.getByRole("button",{name:"Save IB Record"}).click();
  await expect(page.getByText("Enter a valid HTTPS YouTube URL.",{exact:true})).toBeVisible();
  await page.getByLabel("YouTube URL",{exact:true}).fill("https://youtube.com/@qademo");
  await page.getByRole("button",{name:"Save IB Record"}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await page.reload();
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("QA Persistence Client");
  await expect(page.locator("tbody tr")).toHaveCount(1);
  await page.getByRole("button",{name:"Actions for QA Persistence Client"}).click();
  await page.getByRole("button",{name:"Edit record",exact:true}).click();
  await page.getByLabel("Total Salary",{exact:true}).fill("6500");
  await page.getByRole("button",{name:"Save Changes"}).click();
  await expect(page).toHaveURL(/\/ib-records$/);
  await page.getByRole("textbox",{name:"Search records",exact:true}).fill("QA Persistence Client");
  await expect(page.locator("tbody")).toContainText("$6,500.00");
});
test("Excel preview prevents invalid and duplicate rows from being silently committed", async ({page}) => {
  await login(page);
  const existing=seedRecords()[0];
  const newRecord={...existing,clientName:"QA Excel Client",channelName:"QA Excel Channel"};
  const badRecord={...existing,clientName:"QA Invalid Client",payoutDate:"not-a-date"};
  const payload=createWorkbook([newRecord,existing,badRecord]);
  await page.goto("/ib-records/add");
  await page.getByRole("tab",{name:"Import Excel"}).click();
  await page.getByLabel("Upload Excel file",{exact:true}).setInputFiles({name:"qa-records.xlsx",mimeType:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",buffer:payload});
  await expect(page.getByText("3 rows detected",{exact:true})).toBeVisible();
  await expect(page.getByText("1 Possible duplicates",{exact:true})).toBeVisible();
  await expect(page.getByText("1 Invalid",{exact:true})).toBeVisible();
  const before=await (await page.request.get("/api/ib-records")).json();
  expect(before.records.some(r=>r.clientName==="QA Excel Client")).toBe(false);
  await page.getByRole("button",{name:"Import 1 valid records",exact:true}).click();
  await expect(page.getByText("Import complete",{exact:true})).toBeVisible();
  await expect(page.getByText("1 added · 0 updated · 2 skipped",{exact:true})).toBeVisible();
  const after=await (await page.request.get("/api/ib-records")).json();
  expect(after.records.some(r=>r.clientName==="QA Excel Client")).toBe(true);
  expect(after.records.some(r=>r.clientName==="QA Invalid Client")).toBe(false);
  // The server repeats validation even if a client tries to bypass the preview.
  const response=await page.request.post("/api/import",{data:{inputs:[{...newRecord,totalSalary:7000},badRecord],duplicateMode:"update"}});
  expect(await response.json()).toEqual({added:0,updated:1,skipped:1});
  const updated=await (await page.request.get("/api/ib-records")).json();
  expect(updated.records.find(r=>r.clientName==="QA Excel Client").totalSalary).toBe(7000);
});
test("mobile keeps a scrollable table and filters open in a drawer", async ({page}) => {
  await page.setViewportSize({width:390,height:844});
  await login(page);
  await page.screenshot({path:"artifacts/records-mobile.png",fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  expect(await page.locator(".table-scroll").evaluate(el=>el.scrollWidth>el.clientWidth)).toBe(true);
  await page.getByRole("button",{name:"Filters",exact:true}).click();
  await expect(page.getByRole("complementary",{name:"Record filters"})).toBeVisible();
  await page.screenshot({path:"artifacts/filters-mobile.png",fullPage:true});
  await page.getByRole("button",{name:"Close filters",exact:true}).last().click();
  await page.goto("/ib-records/add");
  await page.screenshot({path:"artifacts/add-mobile.png",fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test("logout revokes browser access and forged sessions are rejected", async ({page,context}) => {
  await login(page);
  await page.getByRole("button",{name:/Accountant/}).click();
  await page.getByRole("button",{name:"Sign out",exact:true}).click();
  await expect(page).toHaveURL(/\/login$/);
  expect((await page.request.get("/api/ib-records")).status()).toBe(401);
  await context.addCookies([{name:"bytefx_session",value:"forged.signature",url:"http://127.0.0.1:3100"}]);
  expect((await page.request.get("/api/ib-records")).status()).toBe(401);
});
